# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine

# Install build dependencies
RUN apk add --no-cache gcc musl-dev libffi-dev jpeg-dev zlib-dev

WORKDIR /app

# Copy project files into the container
COPY . .

# Upgrade pip and install runtime dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir httpx 'mcp[cli]>=1.5.0' pillow python-dotenv requests

# Expose the port used by the HTTP server for screenshots
EXPOSE 8011

# Run the MCP server
CMD ["python", "server.py"]
